<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PowerCulprit.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="*" />
    <PackageReference Include="System.Management" Version="*" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="*" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerCulprit.Core\PowerCulprit.Core.csproj" />
    <ProjectReference Include="..\PowerCulprit.Storage\PowerCulprit.Storage.csproj" />
  </ItemGroup>

</Project>
